spring:
  data:
    mongodb:
      username: admin
      password: pass
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecom2.order_service.kafka.OrderConfirmation,paymentConfirmation:com.ecom2.notification_service.kafka.payment
  mail:
    host: localhost
    port: 1025
    username: root
    password: 1234567890
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
